---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: spritsail/docker-build
  settings:
    repo: fivem-dev

- name: publish
  pull: always
  image: spritsail/docker-publish
  settings:
    from: fivem-dev
    repo: spritsail/fivem
    tags:
    - latest
    - "%label org.label-schema.version"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
    - master
    event:
    - push

---
kind: signature
hmac: 3f33d3e3eba462947cdff2d191ccafacfaf2edad59797cb54b85b51475477716

...
